# Generated by Django 5.0 on 2023-12-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
