# Generated by Django 5.0 on 2023-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_departamento_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(default=' ', max_length=20, verbose_name='Nombre Corto'),
            preserve_default=False,
        ),
    ]
