# Generated by Django 5.0 on 2023-12-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_departamento_shor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
